Initialize git in copied revisions to resolve setuptools-scm issues.
Fixes #26.

The following error message arises when using `setuptools-scm`:

```
LookupError: setuptools-scm was unable to detect version for ...

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

      Alternatively, set the version with the environment variable SETUPTOOLS_SCM_PRETEND_VERSION_FOR_${NORMALIZED_DIST_NAME} as described in https://setuptools-scm.readthedocs.io/en/latest/config.
      [end of output]
```

This can be resolved by creating an empty git respository.